---
title: "PCA_ALD_viz"
author: "Steven Black"
date: "4/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries 
```{r}
library("factoextra")
```


## Data 
```{r}
ALD <- read.csv("data/Ordered Team4-ALD_4cohort_dataset.csv")
cohorts <- c("control_avg", "control_AC_avg", "mild_AH_avg", "severe_AH_avg")
```


### Group Data 
```{r}
control <- ALD[1:25, 3:152]
control_AC <- ALD[26:45, 3:152]
mild_AH <- ALD[46:55, 3:152]
severe_AH <- ALD[56:78, 3:152]
```

### Average each group 
```{r}
control_avg <- colMeans(control)
control_AC_avg <- colMeans(control_AC)
mild_AH_avg <- colMeans(mild_AH)
severe_AH_avg <- colMeans(severe_AH)
```

### Combine all groups 
```{r}
all <- rbind(control_avg, control_AC_avg, mild_AH_avg, severe_AH_avg)
```

## PCA 
```{r}
all_pca <- prcomp(all, scale=TRUE)
summary(all_pca)
```

### Viz PCA 
```{r}
fviz_pca(all_pca, label = "none",
                title = "Bacterial Species in Four Cohorts ALD",
                habillage =  c("control_avg", "control_AC_avg", "mild_AH_avg", "severe_AH_avg"),
                addElipses = TRUE, ellipse.level=0.95,
                col.circle = "blue",
                invisible = "var",
                ggtheme=theme_minimal())

```

```{r}
fviz_pca_var(all_pca,                 
             title = "Bacterial Species in Four Cohorts ALD",
             col.ind = colnames(all), 
             label="none", addElipse=TRUE)
```

```{r}
fviz_pca_ind(all_pca,                 
             title = "Bacterial Species in Four Cohorts ALD",
             col.ind = c("control_avg", "control_AC_avg", "mild_AH_avg", "severe_AH_avg"), 
             label="none", addElipse=TRUE)
```

## Transoform Data and perform PCA
```{r}
t_all <- t(all)
t_all_pca <- prcomp(t_all, scale=TRUE)
summary(t_all_pca)
```

### Visualize transformed PCA 
```{r}
fviz_pca(t_all_pca, 
                title = "150 Bacterial Species in Four Cohorts",
                addEllipses = TRUE,
                ellipse.level=0.95,
                ellipse.type="confidence",
                geom.ind = "point",
                pointshape = 21,
                pointsize = 2,
                palette = "jco",
                label = "var",
                # Variables
                alpha.var ="contrib", col.var = "contrib",
                gradient.cols = "RdBu"
                )
```

```{r}
fviz_pca_biplot(t_all_pca, label = "var",
                title = "Bacterial Species in Four Cohorts ALD",
                addElipses = TRUE, elipse.level=1,
                ggtheme=theme_minimal())
```


